### ISSUE TITLE
翻译的显示位置不对

### ISSUE THREAD

**Issue by Kennnnnnji** [muhz9786/tweet-transbook#1]
![image](https://user-images.githubusercontent.com/34367558/103132947-7a19da80-46e2-11eb-91c7-d1860e41383f.png)
如图，翻译显示在了推的最下面……
期望应该是显示在发推时间的上面？

**Comment by seiya0v0** [comment]
收到，这两天有空了修改一下。

**Comment by seiya0v0** [comment]
问题已修正，顺便解决了截图里有分割线的问题

**Comment by Kennnnnnji** [comment]
请问缺少了一个模块`'easylog'`怎么安装？pip里没有搜到
```
python D:\Softs\tweet-transbook\startup.py
Traceback (most recent call last):
  File "D:\Softs\tweet-transbook\startup.py", line 1, in <module>
    import server
  File "D:\Softs\tweet-transbook\server.py", line 8, in <module>
    import auto
  File "D:\Softs\tweet-transbook\auto.py", line 5, in <module>
    from easylog import log
ModuleNotFoundError: No module named 'easylog'
```
```
pip install easylog
ERROR: Could not find a version that satisfies the requirement easylog (from versions: none)
ERROR: No matching distribution found for easylog
```

**Comment by Kennnnnnji** [comment]
@muhz9786 或者能不能加一个`requirements.txt`，方便安装依赖？

**Comment by seiya0v0** [comment]
哦那个是我随便写的测试用的log哈哈哈，你把那个import删掉就行了，我忘记删了

**Comment by Kennnnnnji** [comment]
www
行，安装了selenium能用了

**Comment by seiya0v0** [comment]
除了selenium都用的标准库，安个selenium就行了

**Comment by Kennnnnnji** [comment]
另外从别人的烤推机那随便毛了个模板，用上去好像出错了（`{T}`那里）
![image](https://user-images.githubusercontent.com/34367558/103209355-e6dce100-493d-11eb-8bff-c85729315f5c.png)

模板代码应该没问题

**Comment by seiya0v0** [comment]
图片要放在项目的文件夹里，不然服务器找不到，然后路径改成相对路径
比如你把图片放在static文件夹里
```<img src="./static/xxx.png">```

**Comment by Kennnnnnji** [comment]
嗯嗯，图片这个知道
主要是{T}那里？

**Comment by seiya0v0** [comment]
我也不知道那个T是啥，看着像动态网页上的占位符

**Comment by Kennnnnnji** [comment]
![image](https://user-images.githubusercontent.com/34367558/103209428-0d028100-493e-11eb-8aba-a40e8e440f08.png)
是从夏组的鸡上毛的_(:з」∠)_

**Comment by Kennnnnnji** [comment]
好像删了没啥影响_(:з」∠)_

另外请问模板可以自动保存方便下一次使用吗？
